#!/bin/bash env
# script that sets up ufw so that it bloks all incoming traffic, except the
following TCP ports: 22 (SSH) 443 (HTTPS SSL) 80 (HTTP)
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
